framework:
    messenger:
        default_bus: commands_and_queries_bus

        buses:
            commands_and_queries_bus:
                middleware:
                    - 'App\Middleware\AuditMiddleware'

            events_bus:
                middleware:
                    - 'messenger.middleware.allow_no_handler'

        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
